name: radial_menu_pro
description: "A customizable radial menu widget for Flutter that expands items in various directions and quadrants."
version: 1.0.3
repository: https://github.com/MonkeyLautee/radial_menu_pro
issue_tracker: https://github.com/MonkeyLautee/radial_menu_pro/issues
homepage: https://monkeynote.app/corp
environment:
  sdk: ^3.11.5
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter: